spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/postgres
        username: postgres
        password:
        driverClassName: org.postgresql.Driver
        initialization-mode: always
        initialize: true
        continue-on-error: true
    jpa:
        hibernate :
            dialect : org.hibernate.dialect.PostgreSQLDialect
        ddl-auto : update
        show_sql : true
        format_sql : true

# setting log level
# hibernate? ???? ?? sql ?? ??? ??.
logging:
    level:
        org.hibernate.SQL : debug
        org.hibernate.type : trace